version: '3.8'

services:
  # ----------------------------
  # INFRAESTRUCTURA
  # ----------------------------
  mysqldb:
    image: mysql:8.0
    container_name: barberia-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_catalog
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - barberia-network

  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - barberia-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/

  # ----------------------------
  # MICROSERVICIOS
  # ----------------------------
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      # FIX MANUAL ROUTES
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: auth-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/auth-service/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: catalog-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://catalog-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/catalog-service/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: booking-service
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://booking-service:8083
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/booking-service/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0: StripPrefix=1
    depends_on:
      - service-registry
    networks:
      - barberia-network
    restart: on-failure

  catalog-service:
    build:
      context: .
      dockerfile: catalog-service/Dockerfile
    container_name: catalog-service
    ports:
      - "8082:8082"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_catalog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - mysqldb
      - service-registry
    networks:
      - barberia-network
    restart: on-failure

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    ports:
      - "8083:8083"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_booking?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - mysqldb
      - service-registry
    networks:
      - barberia-network
    restart: on-failure

  frontend-service:
    build:
      context: .
      dockerfile: frontend-service/Dockerfile
    container_name: frontend-service
    ports:
      - "8084:8084"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms128m"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      BACKEND_GATEWAY_URL: http://api-gateway:8080
    depends_on:
      - api-gateway
      - service-registry
    networks:
      - barberia-network
    restart: on-failure

volumes:
  mysql-data:


networks:
  barberia-network:
    driver: bridge
