server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: catalog-service
          uri: http://catalog-service:8082
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/booking-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true # Keep enabled just in case, but explicit routes take precedence
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
